### ISSUE TITLE
关于input拖拽

### ISSUE THREAD

**Issue by JieAlice** [nihaojob/DragLayout#3]
我看到demo里面input拖拽后，input不能输入， 我也用到这个，发现input这个问题不知道该怎么解决，你有好的解决方式吗？

**Comment by nihaojob** [comment]
> 我看到demo里面输入拖拽后，input不能输入，我也用到这个，发现input这个问题不知道该怎么解决，你有好的解决方式吗？

输入需要依赖于input的change事件，我没有在例子里体现，可以自己加一下

**Comment by JieAlice** [comment]
嗯，明白。我这边是点击光标上去然后光标又取消了，没办法输入，还在寻找问题，我看你的demo光标是可以进去的。我再找找问题

**Comment by nihaojob** [comment]
f

> 嗯，明白。我这边是点击光标上去然后光标又取消了，没办法输入，还在寻找问题，我看你的demo光标是可以进去的。我再找找问题

对比一下ant Design的版本，或者提供一个可以复现的版本，咱们一起解决下

**Comment by JieAlice** [comment]
我把项目提交到git上了，internally-piloting就是，测试页面就是我试用的拖拽，刚开始用react，望指导

**Comment by JieAlice** [comment]
邀请你了，https://github.com/JieAlice/internally-piloting

**Comment by nihaojob** [comment]
> 邀请你了，https://github.com/JieAlice/internally-piloting

我看你的用的是 `2.0.11`的版本，我例子里使用的是`1.5.1`

https://github.com/nihaojob/DragLayout/blob/master/package.json#L68

猜想可能是react-sortablejs对拖动元素做过处理，可以看看react-sortablejs 是否和这个问题一致  https://github.com/SortableJS/react-sortablejs/issues/63

你要是解决了 最好分享下   哈哈 😀

**Comment by JieAlice** [comment]
我按照你的demo思路来了一遍，适应到2.0上还是可以的，2.0本身携带的修改id产生的问题我直接绕过去了，等闲下来再看看input的问题，哈哈哈哈哈
