### ISSUE TITLE
[问题]

### ISSUE THREAD

**Issue by zoro-r** [nihaojob/DragLayout#5]
代码clone下来,并没有你demo中的效果, 我看其中的`if (newItem.name === 'Containers') {
      const ComponentsInfo = _.cloneDeep(GlobalComponent[newItem.name]);
      // 判断是否包含默认数据
      newItem.children = [];
    }`

等地方都做了删除操作, 源码不方便提供对吗?

**Comment by nihaojob** [comment]
> 代码clone下来,并没有你demo中的效果, 我看其中的`if (newItem.name === 'Containers') { const ComponentsInfo = _.cloneDeep(GlobalComponent[newItem.name]); // 判断是否包含默认数据 newItem.children = []; }`
> 
> 等地方都做了删除操作, 源码不方便提供对吗?



实例中的效果是有的，而且在现在的演示中也可以操作。
![](https://user-gold-cdn.xitu.io/2019/10/20/16de8cab1fc829e4?w=1046&h=549&f=gif&s=805784)

建议检查下react-sortablejs的版本，很多同学有反馈。
