### ISSUE TITLE
[问题]ref={c => c && (this.sortable = c.sortable)}

### ISSUE THREAD

**Issue by ajie425** [nihaojob/DragLayout#6]
这行代码可以解释一下吗？实在是没有找到sortable在哪里得到的

**Comment by nihaojob** [comment]
> 这行代码可以解释一下吗？实在是没有找到sortable在哪里得到的

拖拽排序是依赖的 sortable：
https://github.com/nihaojob/DragLayout/blob/83e698503d66ebd7511b48d06505479963328394/src/pages/test.jsx#L3

检查下package.json中 react-sortablejs的版本号是否一致：
https://github.com/nihaojob/DragLayout/blob/83e698503d66ebd7511b48d06505479963328394/package.json#L68
