### ISSUE TITLE
【问题】请问拖拽之后的DOM是如何让他不显示的啊，我这里怎么拖拽过去了，克隆的DOM总显示在上面。

### ISSUE THREAD

**Issue by tianfeng65** [nihaojob/DragLayout#7]
![image](https://user-images.githubusercontent.com/39827055/105027040-3e2c2800-5a8a-11eb-9891-0995b844c900.png)
就像上图，红色框框是拖拽过来的，我不想显示它，只想显示自己渲染的另外两个框框，这个怎么做的呢？🙏

**Comment by yanhangtian** [comment]
我也遇到同样的问题，请问解决了吗

**Comment by nihaojob** [comment]
> 我也遇到同样的问题，请问解决了吗

@tianfeng65 已经解决了， 删除在onAdd中手动把那个克隆的元素删了就可以

**Comment by yanhangtian** [comment]
刚才发现在sortable组件上加key属性，就不会出现这种情况
