### ISSUE TITLE
[问题] 对你很感兴趣， 可以认识下吗？

### ISSUE THREAD

**Issue by betseyliu** [nihaojob/DragLayout#9]
**问题描述** [详细地描述问题，让大家都能理解]

**示例代码** [如果有必要，展示代码，线上示例，或仓库]

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by nihaojob** [comment]
微信：13146890191

> **问题描述** [详细地描述问题，让大家都能理解]
> 
> **示例代码** [如果有必要，展示代码，线上示例，或仓库]
> 
> **其他信息** [如截图等其他信息可以贴在这里]
